### ISSUE TITLE
我也想搞这个源码，把项目文件下载了上传到服务器不行啊

### ISSUE THREAD

**Issue by landiao2015** [Hootrix/linkFrontEnd#1]
我也想搞这个源码，把项目文件下载了上传到服务器不行啊，大佬能不能帮忙一下

**Comment by landiao2015** [comment]
大佬能不能出个视频教程

**Comment by Hootrix** [comment]
> 大佬能不能出个视频教程

😂抱歉了。没出教程。
这就是普通的Vue.js项目
```
#安装node.js npm
$ npm install
$ npm run dev#开发调试
$ npm run build#构建项目
```

**Comment by landiao2015** [comment]
> > 大佬能不能出个视频教程
> 
> 抱歉了。没出教程。
> 这就是普通的Vue.js项目
> 
> ```
> #安装node.js npm
> $ npm install
> $ npm run dev#开发调试
> $ npm run build#构建项目
> ```

留个QQ交流一下
